DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS bookmark;

CREATE TABLE account {
id IDENTITY,
username VARCHAR(25) NOT NULL,
PASSWORD VARCHAR(25) NOT NULL
};

CREATE TABLE bookmark {
id INTEGER IDENTITY PRIMARY KEY,
account INTEGER NOT NULL,
description VARCHAR(2000) NOT NULL,
uri VARCHAR (160) NOT NULL,
FOREIGN KEY (account) REFERENCES account(id)
};